### ISSUE TITLE
你好，我有个企业微信审批接口的pr想要提交，但是貌似我提交不了新的分支

### ISSUE THREAD

**Issue by YangCSir** [zsmhub/workweixin#2]
13:41:56.018: [workweixin] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/approval:refs/heads/approval --set-upstream
remote: Permission to zsmhub/workweixin.git denied to YangCSir.
fatal: unable to access 'https://github.com/zsmhub/workweixin.git/': The requested URL returned error: 403

**Comment by zsmhub** [comment]
你的pr流程不正确，需要先fork然后再pr，你先看下这个github pr教程：
https://chinese.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github/

**Comment by YangCSir** [comment]
好的，已提pr
